$('.viewWrap_2').hide();
$('.viewB_1').click(function(){
  $('.viewWrap_2').hide();
  $('.viewWrap_1').show();
  $('.viewB_1').addClass('active');
  $('.viewB_2').removeClass('active');
})
$('.viewB_2').click(function(){
  $('.viewWrap_1').hide();
  $('.viewWrap_2').show();
  $('.viewB_2').addClass('active');
  $('.viewB_1').removeClass('active');
})